import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, replacements?: { [key: string]: string | number }) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    employees: 'Employees',
    recruitment: 'Recruitment',
    performance: 'Performance',
    payroll: 'Payroll & Wages',
    leave: 'Leave Management',
    attendance: 'Attendance',
    training: 'Training',
    benefits: 'Benefits',
    analytics: 'Analytics',
    settings: 'Settings',

    // App Placeholders
    hrAnalytics: 'HR Analytics',
    analyticsDesc: 'Advanced analytics and reporting features coming soon...',
    systemSettings: 'System Settings',
    settingsDesc: 'System configuration and preferences coming soon...',

    // Header
    manager: 'Manager',
    profile: 'Profile',
    notifications: 'Notifications',
    
    // Dashboard
    totalEmployees: 'Total Employees',
    activeRecruitment: 'Active Recruitment',
    pendingLeave: 'Pending Leave Requests',
    upcomingTraining: 'Upcoming Training',
    newHires: 'New Hires This Month',
    turnoverRate: 'Turnover Rate',
    averageSalary: 'Average Salary',
    satisfactionScore: 'Employee Satisfaction',
    vsLastMonth: 'vs last month',
    employeeGrowthTrend: 'Employee Growth Trend',
    departmentDistribution: 'Department Distribution',
    recentActivities: 'Recent Activities',
    leaveRequestsThisMonth: 'Leave Requests This Month',
    newEmployeeOnboarded: 'New employee onboarded',
    performanceReviewCompleted: 'Performance review completed',
    leaveRequestApproved: 'Leave request approved',
    trainingSessionCompleted: 'Training session completed',
    twoHoursAgo: '2 hours ago',
    fourHoursAgo: '4 hours ago',
    sixHoursAgo: '6 hours ago',
    oneDayAgo: '1 day ago',
    totalEmployeesTooltip: 'Total Employees',
    newHiresTooltip: 'New Hires',
    employeesUnit: 'employees',

    // Employee Management
    manageWorkforce: 'Manage your workforce effectively',
    confirmDeleteEmployee: 'Are you sure you want to delete this employee?',
    importSuccess: '{count} employees imported successfully!',
    importNoData: 'No valid employee data found in the file.',
    importFailed: 'Failed to import employees. Please check the file format.',
    departmentAll: 'Department - All',
    employeeCount: '{count} of {total} employees',
    paginationResults: 'Showing {start} to {end} of {total} results',
    previous: 'Previous',
    next: 'Next',
    editEmployee: 'Edit Employee',
    viewEmployeeDetails: 'View Employee Details',
    firstName: 'First Name',
    lastName: 'Last Name',
    selectDepartment: 'Select Department',
    close: 'Close',
    
    // Leave Management
    manageLeave: 'Manage employee leave and sickness requests',
    newLeaveRequest: 'New Leave Request',
    selectEmployeeAlert: 'Please select an employee.',
    allStatus: 'All Status',
    allTypes: 'All Types',
    annualLeave: 'Annual Leave',
    sickLeave: 'Sick Leave',
    personalLeave: 'Personal Leave',
    maternityLeave: 'Maternity Leave',
    emergencyLeave: 'Emergency Leave',
    requestCount: '{count} of {total} requests',
    employee: 'Employee',
    type: 'Type',
    duration: 'Duration',
    dates: 'Dates',
    reason: 'Reason',
    daysUnit: '{count} days',
    dateTo: 'to',
    approve: 'Approve',
    reject: 'Reject',
    selectEmployee: 'Select an employee',
    leaveType: 'Leave Type',
    dateRange: 'Date Range',
    submitRequest: 'Submit Request',
    pendingRequests: 'Pending Requests',
    approvedThisMonth: 'Approved This Month',
    totalDaysRequested: 'Total Days Requested',
    avgProcessingTime: 'Average Processing Time',
    daysValue: '{count} days',

    // Training Management
    manageTraining: 'Manage employee training and development programs',
    createTrainingProgram: 'Create Training Program',
    allCategories: 'All Categories',
    programCount: '{count} of {total} programs',
    instructor: 'Instructor',
    enrollmentProgress: 'Enrollment Progress',
    enrollmentFraction: '{enrolled}/{capacity} ({percent}%)',
    enrollEmployees: 'Enroll Employees',
    viewProgress: 'View Progress',
    viewResults: 'View Results',
    programTitle: 'Program Title',
    description: 'Description',
    capacity: 'Capacity',
    category: 'Category',
    createProgram: 'Create Program',
    activePrograms: 'Active Programs',
    totalEnrolled: 'Total Enrolled',
    upcomingPrograms: 'Upcoming Programs',
    completionRate: 'Completion Rate',

    // Attendance Management
    manageAttendance: 'Track and manage employee attendance',
    alreadyCheckedIn: 'This employee has already checked in today.',
    recordCount: '{count} records',
    hoursUnit: '{count}h',
    checkInEmployee: 'Check In Employee',
    select: '-- Select --',
    confirmCheckIn: 'Confirm Check In',
    checkOutEmployee: 'Check Out Employee',
    noEmployeesCheckedIn: 'No employees are currently checked in.',
    confirmCheckOut: 'Confirm Check Out',
    presentToday: 'Present Today',
    lateArrivals: 'Late Arrivals',
    absent: 'Absent',
    averageHours: 'Average Hours',

    // Payroll Management
    managePayroll: 'Manage employee payroll, wages, and compensation',
    exportReport: 'Export Report',
    allPeriods: 'All Periods',
    totalGrossPay: 'Total Gross Pay',
    totalNetPay: 'Total Net Pay',
    totalDeductions: 'Total Deductions',
    processedRecords: 'Processed Records',
    period: 'Period',
    processPayrollForPeriod: 'Process Payroll for Period',
    selectPeriod: 'Select Period',
    noDraftsToProcess: 'No draft payrolls to process for this period.',
    confirmProcess: 'Confirm Process',

    // Performance Management
    managePerformance: 'Manage employee performance reviews and evaluations',
    createReview: 'Create Review',
    reviewCount: '{count} reviews',
    reviewedBy: 'Reviewed by: {name}',
    continueReview: 'Continue Review',
    viewDetails: 'View Details',
    createPerformanceReview: 'Create Performance Review',
    goalsPlaceholder: 'Goals (one per line)',
    achievementsPlaceholder: 'Achievements (one per line)',
    improvementAreasPlaceholder: 'Improvement Areas (one per line)',
    createDraft: 'Create Draft',
    totalReviews: 'Total Reviews',
    averageRating: 'Average Rating',
    completedReviews: 'Completed Reviews',
    pendingReviews: 'Pending Reviews',

    // Recruitment Management
    manageRecruitment: 'Manage job postings and candidate applications',
    jobCount: '{count} results',
    jobTypeFullTime: 'Full-time',
    jobTypePartTime: 'Part-time',
    jobTypeContract: 'Contract',
    jobTypeIntern: 'Intern',
    applicationsCount: '{count} applications',
    postedDateLabel: 'Posted {date}',
    candidate: 'Candidate',
    experience: 'Experience',
    skills: 'Skills',
    appliedDate: 'Applied Date',
    experienceYears: '{count} years',
    moreSkills: '+{count}',
    editJobPosting: 'Edit Job Posting',
    jobTitlePlaceholder: 'Job Title',
    locationPlaceholder: 'Location',
    minSalaryPlaceholder: 'Min Salary',
    maxSalaryPlaceholder: 'Max Salary',
    jobDescriptionPlaceholder: 'Job Description',
    requirementsPlaceholder: 'Requirements (one per line)',
    activeJobs: 'Active Jobs',
    totalApplications: 'Total Applications',
    interviewsScheduled: 'Interviews Scheduled',
    hiredThisMonth: 'Hired This Month',
    
    // Employee Management
    addEmployee: 'Add Employee',
    employeeList: 'Employee List',
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone',
    department: 'Department',
    position: 'Position',
    hireDate: 'Hire Date',
    status: 'Status',
    actions: 'Actions',
    
    // Authentication
    login: 'Login',
    logout: 'Logout',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    rememberMe: 'Remember Me',
    welcome: 'Welcome to IndustryHR',
    signInToContinue: 'Sign in to continue',
    
    // Attendance
    checkIn: 'Check In',
    checkOut: 'Check Out',
    totalHours: 'Total Hours',
    location: 'Location',
    attendanceReport: 'Attendance Report',
    workingHours: 'Working Hours',
    
    // Payroll
    payrollManagement: 'Payroll & Wages',
    baseSalary: 'Base Salary',
    overtime: 'Overtime',
    bonuses: 'Bonuses',
    deductions: 'Deductions',
    grossPay: 'Gross Pay',
    netPay: 'Net Pay',
    payDate: 'Pay Date',
    processPayroll: 'Process Payroll',
    
    // Performance
    performanceReview: 'Performance Review',
    overallRating: 'Overall Rating',
    goals: 'Goals',
    achievements: 'Achievements',
    improvementAreas: 'Improvement Areas',
    reviewPeriod: 'Review Period',
    
    // Recruitment
    jobPostings: 'Job Postings',
    candidates: 'Candidates',
    applications: 'Applications',
    jobTitle: 'Job Title',
    jobType: 'Job Type',
    createJob: 'Create Job Posting',
    
    // Benefits
    manageEmployeeBenefits: 'Manage employee benefits, insurance, and safety incidents.',
    insurance: 'Insurance',
    workAccidents: 'Work Accidents',
    workCertificates: 'Work Certificates',
    addPolicy: 'Add Policy',
    reportAccident: 'Report Accident',
    requestCertificate: 'Request Certificate',
    policyNumber: 'Policy Number',
    provider: 'Provider',
    coverage: 'Coverage',
    premium: 'Premium',
    healthInsurance: 'Health Insurance',
    lifeInsurance: 'Life Insurance',
    disabilityInsurance: 'Disability Insurance',
    accidentDate: 'Accident Date',
    accidentLocation: 'Accident Location',
    accidentDescription: 'Accident Description',
    severity: 'Severity',
    minor: 'Minor',
    moderate: 'Moderate',
    severe: 'Severe',
    critical: 'Critical',
    followUpActions: 'Follow-up Actions',
    certificateType: 'Certificate Type',
    workCertificate: 'Work Certificate',
    salaryCertificate: 'Salary Certificate',
    issueCertificate: 'Issue Certificate',
    issueDate: 'Issue Date',
    issuedBy: 'Issued By',
    requestDate: 'Request Date',
    allSeverities: 'All Severities',
    reported: 'Reported',
    investigating: 'Investigating',
    requested: 'Requested',
    issued: 'Issued',
    downloaded: 'Downloaded',
    addNewPolicy: 'Add New Policy',
    policyType: 'Policy Type',
    coverageAmount: 'Coverage Amount',
    monthlyPremium: 'Monthly Premium',
    startDate: 'Start Date',
    reportNewAccident: 'Report New Accident',
    followUpActionsPlaceholder: 'Describe follow-up actions taken...',
    requestNewCertificate: 'Request New Certificate',

    // Analytics
    analyticsAndReporting: 'Analytics & Reporting',
    deepDive: 'Deep dive into your workforce data',
    headcountOverview: 'Headcount Overview',
    genderDistribution: 'Gender Distribution',
    ageDistribution: 'Age Distribution',
    salaryDistribution: 'Salary Distribution',
    recruitmentFunnel: 'Recruitment Funnel',
    turnoverRateOverTime: 'Turnover Rate Over Time',
    male: 'Male',
    female: 'Female',
    other: 'Other',

    // Settings
    manageSettings: 'Manage your profile and system settings',
    company: 'Company',
    appearance: 'Appearance',
    saveChanges: 'Save Changes',
    passwordUpdated: 'Password updated successfully!',
    profileUpdated: 'Profile updated successfully!',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    changePassword: 'Change Password',
    notificationPreferences: 'Notification Preferences',
    emailNotifications: 'Email Notifications',
    inAppNotifications: 'In-App Notifications',
    leaveRequests: 'Leave Requests',
    performanceReviews: 'Performance Reviews',
    newCandidates: 'New Candidates',
    companySettings: 'Company Settings',
    manageDepartments: 'Manage Departments',
    addNew: 'Add New',
    manageJobTitles: 'Manage Job Titles',
    manageLeavePolicies: 'Manage Leave Policies',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',

    // Common
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    import: 'Import',
    active: 'Active',
    inactive: 'Inactive',
    onLeave: 'On Leave',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    draft: 'Draft',
    completed: 'Completed',
    processed: 'Processed',
    paid: 'Paid',
    
    // Departments
    engineering: 'Engineering',
    manufacturing: 'Manufacturing',
    quality: 'Quality Assurance',
    maintenance: 'Maintenance',
    safety: 'Safety & Health',
    logistics: 'Logistics',
    finance: 'Finance',
    hr: 'Human Resources',
    it: 'Information Technology',
    management: 'Management'
  },
  fr: {
    // Navigation
    dashboard: 'Tableau de Bord',
    employees: 'Employés',
    recruitment: 'Recrutement',
    performance: 'Performance',
    payroll: 'Paie et Salaires',
    leave: 'Gestion des Congés',
    attendance: 'Présence',
    training: 'Formation',
    benefits: 'Avantages Sociaux',
    analytics: 'Analyses',
    settings: 'Paramètres',

    // App Placeholders
    hrAnalytics: 'Analyses RH',
    analyticsDesc: 'Fonctionnalités avancées d\'analyse et de reporting bientôt disponibles...',
    systemSettings: 'Paramètres du Système',
    settingsDesc: 'Configuration du système et préférences bientôt disponibles...',

    // Header
    manager: 'Manager',
    profile: 'Profil',
    notifications: 'Notifications',
    
    // Dashboard
    totalEmployees: 'Total Employés',
    activeRecruitment: 'Recrutement Actif',
    pendingLeave: 'Demandes de Congé en Attente',
    upcomingTraining: 'Formation à Venir',
    newHires: 'Nouvelles Embauches ce Mois',
    turnoverRate: 'Taux de Rotation',
    averageSalary: 'Salaire Moyen',
    satisfactionScore: 'Satisfaction des Employés',
    vsLastMonth: 'vs le mois dernier',
    employeeGrowthTrend: 'Tendance de Croissance des Employés',
    departmentDistribution: 'Répartition par Département',
    recentActivities: 'Activités Récentes',
    leaveRequestsThisMonth: 'Demandes de Congé ce Mois',
    newEmployeeOnboarded: 'Nouvel employé intégré',
    performanceReviewCompleted: 'Évaluation de performance terminée',
    leaveRequestApproved: 'Demande de congé approuvée',
    trainingSessionCompleted: 'Session de formation terminée',
    twoHoursAgo: 'il y a 2 heures',
    fourHoursAgo: 'il y a 4 heures',
    sixHoursAgo: 'il y a 6 heures',
    oneDayAgo: 'il y a 1 jour',
    totalEmployeesTooltip: 'Total des Employés',
    newHiresTooltip: 'Nouvelles Embauches',
    employeesUnit: 'employés',

    // Employee Management
    manageWorkforce: 'Gérez efficacement votre personnel',
    confirmDeleteEmployee: 'Êtes-vous sûr de vouloir supprimer cet employé ?',
    importSuccess: '{count} employés importés avec succès !',
    importNoData: 'Aucune donnée d\'employé valide trouvée dans le fichier.',
    importFailed: 'Échec de l\'importation des employés. Veuillez vérifier le format du fichier.',
    departmentAll: 'Département - Tous',
    employeeCount: '{count} sur {total} employés',
    paginationResults: 'Affichage de {start} à {end} sur {total} résultats',
    previous: 'Précédent',
    next: 'Suivant',
    editEmployee: 'Modifier l\'Employé',
    viewEmployeeDetails: 'Détails de l\'Employé',
    firstName: 'Prénom',
    lastName: 'Nom',
    selectDepartment: 'Sélectionner un Département',
    close: 'Fermer',

    // Leave Management
    manageLeave: 'Gérez les demandes de congé et d\'arrêt maladie',
    newLeaveRequest: 'Nouvelle Demande de Congé',
    selectEmployeeAlert: 'Veuillez sélectionner un employé.',
    allStatus: 'Tous les Statuts',
    allTypes: 'Tous les Types',
    annualLeave: 'Congé Annuel',
    sickLeave: 'Arrêt Maladie',
    personalLeave: 'Congé Personnel',
    maternityLeave: 'Congé Maternité',
    emergencyLeave: 'Congé d\'Urgence',
    requestCount: '{count} sur {total} demandes',
    employee: 'Employé',
    type: 'Type',
    duration: 'Durée',
    dates: 'Dates',
    reason: 'Raison',
    daysUnit: '{count} jours',
    dateTo: 'au',
    approve: 'Approuver',
    reject: 'Rejeter',
    selectEmployee: 'Sélectionner un employé',
    leaveType: 'Type de Congé',
    dateRange: 'Période',
    submitRequest: 'Soumettre la Demande',
    pendingRequests: 'Demandes en Attente',
    approvedThisMonth: 'Approuvées ce Mois',
    totalDaysRequested: 'Total Jours Demandés',
    avgProcessingTime: 'Temps de Traitement Moyen',
    daysValue: '{count} jours',

    // Training Management
    manageTraining: 'Gérez les programmes de formation et de développement des employés',
    createTrainingProgram: 'Créer un Programme de Formation',
    allCategories: 'Toutes les Catégories',
    programCount: '{count} sur {total} programmes',
    instructor: 'Formateur',
    enrollmentProgress: 'Progression des Inscriptions',
    enrollmentFraction: '{enrolled}/{capacity} ({percent}%)',
    enrollEmployees: 'Inscrire des Employés',
    viewProgress: 'Voir la Progression',
    viewResults: 'Voir les Résultats',
    programTitle: 'Titre du Programme',
    description: 'Description',
    capacity: 'Capacité',
    category: 'Catégorie',
    createProgram: 'Créer le Programme',
    activePrograms: 'Programmes Actifs',
    totalEnrolled: 'Total Inscrits',
    upcomingPrograms: 'Programmes à Venir',
    completionRate: 'Taux d\'Achèvement',

    // Attendance Management
    manageAttendance: 'Suivez et gérez la présence des employés',
    alreadyCheckedIn: 'Cet employé a déjà pointé aujourd\'hui.',
    recordCount: '{count} enregistrements',
    hoursUnit: '{count}h',
    checkInEmployee: 'Pointer l\'Arrivée d\'un Employé',
    select: '-- Sélectionner --',
    confirmCheckIn: 'Confirmer l\'Arrivée',
    checkOutEmployee: 'Pointer la Sortie d\'un Employé',
    noEmployeesCheckedIn: 'Aucun employé n\'a pointé son arrivée actuellement.',
    confirmCheckOut: 'Confirmer la Sortie',
    presentToday: 'Présents Aujourd\'hui',
    lateArrivals: 'Arrivées en Retard',
    absent: 'Absents',
    averageHours: 'Heures Moyennes',

    // Payroll Management
    managePayroll: 'Gérez la paie, les salaires et la rémunération des employés',
    exportReport: 'Exporter le Rapport',
    allPeriods: 'Toutes les Périodes',
    totalGrossPay: 'Salaire Brut Total',
    totalNetPay: 'Salaire Net Total',
    totalDeductions: 'Total des Déductions',
    processedRecords: 'Dossiers Traités',
    period: 'Période',
    processPayrollForPeriod: 'Traiter la Paie pour la Période',
    selectPeriod: 'Sélectionner la Période',
    noDraftsToProcess: 'Aucune paie en brouillon à traiter pour cette période.',
    confirmProcess: 'Confirmer le Traitement',

    // Performance Management
    managePerformance: 'Gérez les évaluations de performance des employés',
    createReview: 'Créer une Évaluation',
    reviewCount: '{count} évaluations',
    reviewedBy: 'Évalué par : {name}',
    continueReview: 'Continuer l\'Évaluation',
    viewDetails: 'Voir les Détails',
    createPerformanceReview: 'Créer une Évaluation de Performance',
    goalsPlaceholder: 'Objectifs (un par ligne)',
    achievementsPlaceholder: 'Réalisations (une par ligne)',
    improvementAreasPlaceholder: 'Axes d\'amélioration (un par ligne)',
    createDraft: 'Créer un Brouillon',
    totalReviews: 'Total Évaluations',
    averageRating: 'Note Moyenne',
    completedReviews: 'Évaluations Terminées',
    pendingReviews: 'Évaluations en Attente',

    // Recruitment Management
    manageRecruitment: 'Gérez les offres d\'emploi et les candidatures',
    jobCount: '{count} résultats',
    jobTypeFullTime: 'Plein temps',
    jobTypePartTime: 'Temps partiel',
    jobTypeContract: 'Contrat',
    jobTypeIntern: 'Stage',
    applicationsCount: '{count} candidatures',
    postedDateLabel: 'Publié le {date}',
    candidate: 'Candidat',
    experience: 'Expérience',
    skills: 'Compétences',
    appliedDate: 'Date de Candidature',
    experienceYears: '{count} ans',
    moreSkills: '+{count}',
    editJobPosting: 'Modifier l\'Offre d\'Emploi',
    jobTitlePlaceholder: 'Titre du Poste',
    locationPlaceholder: 'Lieu',
    minSalaryPlaceholder: 'Salaire Min',
    maxSalaryPlaceholder: 'Salaire Max',
    jobDescriptionPlaceholder: 'Description du Poste',
    requirementsPlaceholder: 'Exigences (une par ligne)',
    activeJobs: 'Emplois Actifs',
    totalApplications: 'Total Candidatures',
    interviewsScheduled: 'Entretiens Planifiés',
    hiredThisMonth: 'Embauchés ce Mois-ci',
    
    // Employee Management
    addEmployee: 'Ajouter Employé',
    employeeList: 'Liste des Employés',
    fullName: 'Nom Complet',
    email: 'Email',
    phone: 'Téléphone',
    department: 'Département',
    position: 'Poste',
    hireDate: 'Date d\'Embauche',
    status: 'Statut',
    actions: 'Actions',
    
    // Authentication
    login: 'Connexion',
    logout: 'Déconnexion',
    password: 'Mot de passe',
    forgotPassword: 'Mot de passe oublié?',
    rememberMe: 'Se souvenir de moi',
    welcome: 'Bienvenue à IndustryHR',
    signInToContinue: 'Connectez-vous pour continuer',
    
    // Attendance
    checkIn: 'Pointer l\'Arrivée',
    checkOut: 'Pointer la Sortie',
    totalHours: 'Total Heures',
    location: 'Emplacement',
attendanceReport: 'Rapport de Présence',
    workingHours: 'Heures de Travail',
    
    // Payroll
    payrollManagement: 'Paie et Salaires',
    baseSalary: 'Salaire de Base',
    overtime: 'Heures Supplémentaires',
    bonuses: 'Primes',
    deductions: 'Déductions',
    grossPay: 'Salaire Brut',
    netPay: 'Salaire Net',
    payDate: 'Date de Paiement',
    processPayroll: 'Traiter la Paie',
    
    // Performance
    performanceReview: 'Évaluation de Performance',
    overallRating: 'Note Globale',
    goals: 'Objectifs',
    achievements: 'Réalisations',
    improvementAreas: 'Domaines d\'Amélioration',
    reviewPeriod: 'Période d\'Évaluation',
    
    // Recruitment
    jobPostings: 'Offres d\'Emploi',
    candidates: 'Candidats',
    applications: 'Candidatures',
    jobTitle: 'Titre du Poste',
    jobType: 'Type d\'Emploi',
    createJob: 'Créer une Offre d\'Emploi',

    // Benefits
    manageEmployeeBenefits: 'Gérez les avantages sociaux, l\'assurance et les accidents du travail.',
    insurance: 'Assurance',
    workAccidents: 'Accidents de Travail',
    workCertificates: 'Attestations de Travail',
    addPolicy: 'Ajouter une Police',
    reportAccident: 'Déclarer un Accident',
    requestCertificate: 'Demander une Attestation',
    policyNumber: 'Numéro de Police',
    provider: 'Fournisseur',
    coverage: 'Couverture',
    premium: 'Prime',
    healthInsurance: 'Assurance Maladie',
    lifeInsurance: 'Assurance Vie',
    disabilityInsurance: 'Assurance Invalidité',
    accidentDate: 'Date de l\'Accident',
    accidentLocation: 'Lieu de l\'Accident',
    accidentDescription: 'Description de l\'Accident',
    severity: 'Gravité',
    minor: 'Mineur',
    moderate: 'Modéré',
    severe: 'Grave',
    critical: 'Critique',
    followUpActions: 'Actions de Suivi',
    certificateType: 'Type d\'Attestation',
    workCertificate: 'Attestation de Travail',
    salaryCertificate: 'Attestation de Salaire',
    issueCertificate: 'Émettre l\'Attestation',
    issueDate: 'Date d\'Émission',
    issuedBy: 'Émis par',
    requestDate: 'Date de Demande',
    allSeverities: 'Toutes Gravités',
    reported: 'Déclaré',
    investigating: 'Enquête en cours',
    requested: 'Demandé',
    issued: 'Émis',
    downloaded: 'Téléchargé',
    addNewPolicy: 'Ajouter une Nouvelle Police',
    policyType: 'Type de Police',
    coverageAmount: 'Montant de la Couverture',
    monthlyPremium: 'Prime Mensuelle',
    startDate: 'Date de Début',
    reportNewAccident: 'Déclarer un Nouvel Accident',
    followUpActionsPlaceholder: 'Décrire les actions de suivi...',
    requestNewCertificate: 'Demander une Nouvelle Attestation',

    // Analytics
    analyticsAndReporting: 'Analyses et Rapports',
    deepDive: 'Plongez dans les données de votre personnel',
    headcountOverview: 'Aperçu des Effectifs',
    genderDistribution: 'Répartition par Sexe',
    ageDistribution: 'Répartition par Âge',
    salaryDistribution: 'Répartition des Salaires',
    recruitmentFunnel: 'Entonnoir de Recrutement',
    turnoverRateOverTime: 'Taux de Rotation dans le Temps',
    male: 'Homme',
    female: 'Femme',
    other: 'Autre',

    // Settings
    manageSettings: 'Gérez votre profil et les paramètres du système',
    company: 'Entreprise',
    appearance: 'Apparence',
    saveChanges: 'Enregistrer les Modifications',
    passwordUpdated: 'Mot de passe mis à jour avec succès !',
    profileUpdated: 'Profil mis à jour avec succès !',
    currentPassword: 'Mot de Passe Actuel',
    newPassword: 'Nouveau Mot de Passe',
    confirmPassword: 'Confirmer le Nouveau Mot de Passe',
    changePassword: 'Changer le Mot de Passe',
    notificationPreferences: 'Préférences de Notification',
    emailNotifications: 'Notifications par Email',
    inAppNotifications: 'Notifications dans l\'Application',
    leaveRequests: 'Demandes de Congé',
    performanceReviews: 'Évaluations de Performance',
    newCandidates: 'Nouveaux Candidats',
    companySettings: 'Paramètres de l\'Entreprise',
    manageDepartments: 'Gérer les Départements',
    addNew: 'Ajouter',
    manageJobTitles: 'Gérer les Titres de Poste',
    manageLeavePolicies: 'Gérer les Politiques de Congés',
    theme: 'Thème',
    light: 'Clair',
    dark: 'Sombre',
    system: 'Système',
    
    // Common
    save: 'Sauvegarder',
    cancel: 'Annuler',
    edit: 'Modifier',
    delete: 'Supprimer',
    view: 'Voir',
    search: 'Rechercher',
    filter: 'Filtrer',
    export: 'Exporter',
    import: 'Importer',
    active: 'Actif',
    inactive: 'Inactif',
    onLeave: 'En Congé',
    pending: 'En Attente',
    approved: 'Approuvé',
    rejected: 'Rejeté',
    draft: 'Brouillon',
    completed: 'Terminé',
    processed: 'Traité',
    paid: 'Payé',
    
    // Departments
    engineering: 'Ingénierie',
    manufacturing: 'Fabrication',
    quality: 'Assurance Qualité',
    maintenance: 'Maintenance',
    safety: 'Sécurité et Santé',
    logistics: 'Logistique',
    finance: 'Finance',
    hr: 'Ressources Humaines',
    it: 'Technologies de l\'Information',
    management: 'Direction'
  },
  ar: {
    // Navigation
    dashboard: 'لوحة القيادة',
    employees: 'الموظفين',
    recruitment: 'التوظيف',
    performance: 'الأداء',
    payroll: 'الرواتب والأجور',
    leave: 'إدارة الإجازات',
    attendance: 'الحضور',
    training: 'التدريب',
    benefits: 'المزايا',
    analytics: 'التحليلات',
    settings: 'الإعدادات',

    // App Placeholders
    hrAnalytics: 'تحليلات الموارد البشرية',
    analyticsDesc: 'ميزات التحليلات والتقارير المتقدمة قادمة قريبًا...',
    systemSettings: 'إعدادات النظام',
    settingsDesc: 'تكوين النظام والتفضيلات قادمة قريبًا...',

    // Header
    manager: 'مدير',
    profile: 'الملف الشخصي',
    notifications: 'الإشعارات',
    
    // Dashboard
    totalEmployees: 'إجمالي الموظفين',
    activeRecruitment: 'التوظيف النشط',
    pendingLeave: 'طلبات الإجازة المعلقة',
    upcomingTraining: 'التدريب القادم',
    newHires: 'التعيينات الجديدة هذا الشهر',
    turnoverRate: 'معدل دوران الموظفين',
    averageSalary: 'متوسط الراتب',
    satisfactionScore: 'رضا الموظفين',
    vsLastMonth: 'مقارنة بالشهر الماضي',
    employeeGrowthTrend: 'اتجاه نمو الموظفين',
    departmentDistribution: 'توزيع الأقسام',
    recentActivities: 'الأنشطة الأخيرة',
    leaveRequestsThisMonth: 'طلبات الإجازة هذا الشهر',
    newEmployeeOnboarded: 'تم ضم موظف جديد',
    performanceReviewCompleted: 'اكتمل تقييم الأداء',
    leaveRequestApproved: 'تمت الموافقة على طلب الإجازة',
    trainingSessionCompleted: 'اكتملت جلسة التدريب',
    twoHoursAgo: 'منذ ساعتين',
    fourHoursAgo: 'منذ 4 ساعات',
    sixHoursAgo: 'منذ 6 ساعات',
    oneDayAgo: 'منذ يوم واحد',
    totalEmployeesTooltip: 'إجمالي الموظفين',
    newHiresTooltip: 'تعيينات جديدة',
    employeesUnit: 'موظفين',

    // Employee Management
    manageWorkforce: 'أدر قوتك العاملة بفعالية',
    confirmDeleteEmployee: 'هل أنت متأكد أنك تريد حذف هذا الموظف؟',
    importSuccess: 'تم استيراد {count} موظف بنجاح!',
    importNoData: 'لم يتم العثور على بيانات موظفين صالحة في الملف.',
    importFailed: 'فشل استيراد الموظفين. يرجى التحقق من تنسيق الملف.',
    departmentAll: 'القسم - الكل',
    employeeCount: '{count} من {total} موظفين',
    paginationResults: 'عرض {start} إلى {end} من {total} نتائج',
    previous: 'السابق',
    next: 'التالي',
    editEmployee: 'تعديل الموظف',
    viewEmployeeDetails: 'تفاصيل الموظف',
    firstName: 'الاسم الأول',
    lastName: 'اسم العائلة',
    selectDepartment: 'اختر القسم',
    close: 'إغلاق',

    // Leave Management
    manageLeave: 'إدارة إجازات الموظفين والغياب المرضي',
    newLeaveRequest: 'طلب إجازة جديد',
    selectEmployeeAlert: 'الرجاء اختيار موظف.',
    allStatus: 'جميع الحالات',
    allTypes: 'جميع الأنواع',
    annualLeave: 'إجازة سنوية',
    sickLeave: 'إجازة مرضية',
    personalLeave: 'إجازة شخصية',
    maternityLeave: 'إجازة أمومة',
    emergencyLeave: 'إجازة طارئة',
    requestCount: '{count} من {total} طلبات',
    employee: 'الموظف',
    type: 'النوع',
    duration: 'المدة',
    dates: 'التواريخ',
    reason: 'السبب',
    daysUnit: '{count} أيام',
    dateTo: 'إلى',
    approve: 'موافقة',
    reject: 'رفض',
    selectEmployee: 'اختر موظف',
    leaveType: 'نوع الإجازة',
    dateRange: 'نطاق التاريخ',
    submitRequest: 'إرسال الطلب',
    pendingRequests: 'الطلبات المعلقة',
    approvedThisMonth: 'الموافق عليها هذا الشهر',
    totalDaysRequested: 'إجمالي الأيام المطلوبة',
    avgProcessingTime: 'متوسط وقت المعالجة',
    daysValue: '{count} يوم',

    // Training Management
    manageTraining: 'إدارة برامج تدريب وتطوير الموظفين',
    createTrainingProgram: 'إنشاء برنامج تدريبي',
    allCategories: 'جميع الفئات',
    programCount: '{count} من {total} برامج',
    instructor: 'المدرب',
    enrollmentProgress: 'تقدم التسجيل',
    enrollmentFraction: '{enrolled}/{capacity} ({percent}%)',
    enrollEmployees: 'تسجيل الموظفين',
    viewProgress: 'عرض التقدم',
    viewResults: 'عرض النتائج',
    programTitle: 'عنوان البرنامج',
    description: 'الوصف',
    capacity: 'السعة',
    category: 'الفئة',
    createProgram: 'إنشاء البرنامج',
    activePrograms: 'البرامج النشطة',
    totalEnrolled: 'إجمالي المسجلين',
    upcomingPrograms: 'البرامج القادمة',
    completionRate: 'معدل الإكمال',

    // Attendance Management
    manageAttendance: 'تتبع وإدارة حضور الموظفين',
    alreadyCheckedIn: 'هذا الموظف قد سجل حضوره اليوم بالفعل.',
    recordCount: '{count} سجلات',
    hoursUnit: '{count}س',
    checkInEmployee: 'تسجيل حضور موظف',
    select: '-- اختر --',
    confirmCheckIn: 'تأكيد الحضور',
    checkOutEmployee: 'تسجيل انصراف موظف',
    noEmployeesCheckedIn: 'لا يوجد موظفون مسجلون حاليًا.',
    confirmCheckOut: 'تأكيد الانصراف',
    presentToday: 'حاضرون اليوم',
    lateArrivals: 'الوصول المتأخر',
    absent: 'غائب',
    averageHours: 'متوسط الساعات',

    // Payroll Management
    managePayroll: 'إدارة كشوف المرتبات والأجور والتعويضات',
    exportReport: 'تصدير التقرير',
    allPeriods: 'جميع الفترات',
    totalGrossPay: 'إجمالي الراتب الإجمالي',
    totalNetPay: 'إجمالي الراتب الصافي',
    totalDeductions: 'إجمالي الخصومات',
    processedRecords: 'السجلات المعالجة',
    period: 'الفترة',
    processPayrollForPeriod: 'معالجة الرواتب للفترة',
    selectPeriod: 'اختر الفترة',
    noDraftsToProcess: 'لا توجد مسودات رواتب لمعالجتها لهذه الفترة.',
    confirmProcess: 'تأكيد المعالجة',

    // Performance Management
    managePerformance: 'إدارة تقييمات أداء الموظفين',
    createReview: 'إنشاء تقييم',
    reviewCount: '{count} تقييمات',
    reviewedBy: 'تم التقييم بواسطة: {name}',
    continueReview: 'متابعة التقييم',
    viewDetails: 'عرض التفاصيل',
    createPerformanceReview: 'إنشاء تقييم أداء',
    goalsPlaceholder: 'الأهداف (كل هدف في سطر)',
    achievementsPlaceholder: 'الإنجازات (كل إنجاز في سطر)',
    improvementAreasPlaceholder: 'مجالات التحسين (كل مجال في سطر)',
    createDraft: 'إنشاء مسودة',
    totalReviews: 'إجمالي التقييمات',
    averageRating: 'متوسط التقييم',
    completedReviews: 'التقييمات المكتملة',
    pendingReviews: 'التقييمات المعلقة',

    // Recruitment Management
    manageRecruitment: 'إدارة إعلانات الوظائف وطلبات المرشحين',
    jobCount: '{count} نتائج',
    jobTypeFullTime: 'دوام كامل',
    jobTypePartTime: 'دوام جزئي',
    jobTypeContract: 'عقد',
    jobTypeIntern: 'تدريب',
    applicationsCount: '{count} طلبات',
    postedDateLabel: 'نشر في {date}',
    candidate: 'المرشح',
experience: 'الخبرة',
    skills: 'المهارات',
    appliedDate: 'تاريخ التقديم',
    experienceYears: '{count} سنوات',
    moreSkills: '+{count}',
    editJobPosting: 'تعديل إعلان الوظيفة',
    jobTitlePlaceholder: 'المسمى الوظيفي',
    locationPlaceholder: 'الموقع',
    minSalaryPlaceholder: 'الراتب الأدنى',
    maxSalaryPlaceholder: 'الراتب الأقصى',
    jobDescriptionPlaceholder: 'وصف الوظيفة',
    requirementsPlaceholder: 'المتطلبات (كل متطلب في سطر)',
    activeJobs: 'الوظائف النشطة',
    totalApplications: 'إجمالي الطلبات',
    interviewsScheduled: 'المقابلات المجدولة',
    hiredThisMonth: 'المعينون هذا الشهر',
    
    // Employee Management
    addEmployee: 'إضافة موظف',
    employeeList: 'قائمة الموظفين',
    fullName: 'الاسم الكامل',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    department: 'القسم',
    position: 'المنصب',
    hireDate: 'تاريخ التوظيف',
    status: 'الحالة',
    actions: 'الإجراءات',
    
    // Authentication
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    password: 'كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور؟',
    rememberMe: 'تذكرني',
    welcome: 'مرحباً بك في IndustryHR',
    signInToContinue: 'سجل دخولك للمتابعة',
    
    // Attendance
    checkIn: 'تسجيل الدخول',
    checkOut: 'تسجيل الخروج',
    totalHours: 'إجمالي الساعات',
    location: 'الموقع',
    attendanceReport: 'تقرير الحضور',
    workingHours: 'ساعات العمل',
    
    // Payroll
    payrollManagement: 'الرواتب والأجور',
    baseSalary: 'الراتب الأساسي',
    overtime: 'العمل الإضافي',
    bonuses: 'المكافآت',
    deductions: 'الخصومات',
    grossPay: 'الراتب الإجمالي',
    netPay: 'الراتب الصافي',
    payDate: 'تاريخ الدفع',
    processPayroll: 'معالجة كشوف المرتبات',
    
    // Performance
    performanceReview: 'تقييم الأداء',
    overallRating: 'التقييم العام',
    goals: 'الأهداف',
    achievements: 'الإنجازات',
    improvementAreas: 'مجالات التحسين',
    reviewPeriod: 'فترة التقييم',
    
    // Recruitment
    jobPostings: 'الوظائف المتاحة',
    candidates: 'المرشحين',
    applications: 'الطلبات',
    jobTitle: 'المسمى الوظيفي',
    jobType: 'نوع الوظيفة',
    createJob: 'إنشاء إعلان وظيفي',

    // Benefits
    manageEmployeeBenefits: 'إدارة مزايا الموظفين والتأمين وحوادث العمل.',
    insurance: 'التأمين',
    workAccidents: 'حوادث العمل',
    workCertificates: 'شهادات العمل',
    addPolicy: 'إضافة بوليصة',
    reportAccident: 'الإبلاغ عن حادث',
    requestCertificate: 'طلب شهادة',
    policyNumber: 'رقم البوليصة',
    provider: 'مزود الخدمة',
    coverage: 'التغطية',
    premium: 'القسط',
healthInsurance: 'تأمين صحي',
    lifeInsurance: 'تأمين على الحياة',
    disabilityInsurance: 'تأمين ضد العجز',
    accidentDate: 'تاريخ الحادث',
    accidentLocation: 'مكان الحادث',
    accidentDescription: 'وصف الحادث',
    severity: 'الخطورة',
    minor: 'بسيط',
    moderate: 'متوسط',
    severe: 'شديد',
    critical: 'حرج',
    followUpActions: 'إجراءات المتابعة',
    certificateType: 'نوع الشهادة',
    workCertificate: 'شهادة عمل',
    salaryCertificate: 'شهادة راتب',
    issueCertificate: 'إصدار شهادة',
    issueDate: 'تاريخ الإصدار',
    issuedBy: 'صدرت بواسطة',
    requestDate: 'تاريخ الطلب',
    allSeverities: 'كل الخطورة',
    reported: 'تم الإبلاغ',
    investigating: 'قيد التحقيق',
    requested: 'تم الطلب',
    issued: 'صدرت',
    downloaded: 'تم التنزيل',
    addNewPolicy: 'إضافة بوليصة جديدة',
    policyType: 'نوع البوليصة',
    coverageAmount: 'مبلغ التغطية',
    monthlyPremium: 'القسط الشهري',
    startDate: 'تاريخ البدء',
    reportNewAccident: 'الإبلاغ عن حادث جديد',
    followUpActionsPlaceholder: 'وصف إجراءات المتابعة المتخذة...',
    requestNewCertificate: 'طلب شهادة جديدة',

    // Analytics
    analyticsAndReporting: 'التحليلات والتقارير',
    deepDive: 'تعمق في بيانات القوى العاملة لديك',
    headcountOverview: 'نظرة عامة على عدد الموظفين',
    genderDistribution: 'التوزيع حسب الجنس',
    ageDistribution: 'التوزيع حسب العمر',
    salaryDistribution: 'توزيع الرواتب',
    recruitmentFunnel: 'مسار التوظيف',
    turnoverRateOverTime: 'معدل الدوران عبر الزمن',
    male: 'ذكر',
    female: 'أنثى',
    other: 'آخر',

    // Settings
    manageSettings: 'إدارة ملفك الشخصي وإعدادات النظام',
    company: 'الشركة',
    appearance: 'المظهر',
    saveChanges: 'حفظ التغييرات',
    passwordUpdated: 'تم تحديث كلمة المرور بنجاح!',
    profileUpdated: 'تم تحديث الملف الشخصي بنجاح!',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    confirmPassword: 'تأكيد كلمة المرور الجديدة',
    changePassword: 'تغيير كلمة المرور',
    notificationPreferences: 'تفضيلات الإشعارات',
    emailNotifications: 'إشعارات البريد الإلكتروني',
    inAppNotifications: 'الإشعارات داخل التطبيق',
    leaveRequests: 'طلبات الإجازة',
    performanceReviews: 'تقييمات الأداء',
    newCandidates: 'المرشحون الجدد',
    companySettings: 'إعدادات الشركة',
    manageDepartments: 'إدارة الأقسام',
    addNew: 'إضافة جديد',
    manageJobTitles: 'إدارة المسميات الوظيفية',
    manageLeavePolicies: 'إدارة سياسات الإجازات',
    theme: 'المظهر',
    light: 'فاتح',
    dark: 'داكن',
    system: 'النظام',
    
    // Common
    save: 'حفظ',
    cancel: 'إلغاء',
    edit: 'تعديل',
    delete: 'حذف',
    view: 'عرض',
    search: 'بحث',
    filter: 'تصفية',
    export: 'تصدير',
    import: 'استيراد',
    active: 'نشط',
    inactive: 'غير نشط',
    onLeave: 'في إجازة',
    pending: 'معلق',
    approved: 'موافق عليه',
    rejected: 'مرفوض',
    draft: 'مسودة',
    completed: 'مكتمل',
    processed: 'تمت المعالجة',
    paid: 'مدفوع',
    
    // Departments
    engineering: 'الهندسة',
    manufacturing: 'التصنيع',
    quality: 'ضمان الجودة',
    maintenance: 'الصيانة',
    safety: 'السلامة والصحة',
    logistics: 'اللوجستيات',
    finance: 'المالية',
    hr: 'الموارد البشرية',
    it: 'تكنولوجيا المعلومات',
    management: 'الإدارة'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string, replacements: { [key: string]: string | number } = {}): string => {
    let translation = translations[language][key as keyof typeof translations.en] || key;
    Object.keys(replacements).forEach(placeholder => {
      translation = translation.replace(`{${placeholder}}`, String(replacements[placeholder]));
    });
    return translation;
  };

  const isRTL = language === 'ar';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [isRTL, language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
